### ISSUE TITLE
Pascal VOC support

### ISSUE THREAD

**Issue by JappaB** [cancam/LRP#3]
The github page states that Pascal VOC support should be coming soon. However, there haven't been any commits lately. Are the plans to support Pascal VOC still on?

**Comment by cancam** [comment]
Hi, @JappaB
Sorry for this conflict. We are going to upload the code for PASCAL-VOC evaluation until next Sunday.

**Comment by JappaB** [comment]
Hi @cancam, that's great news! Thanks a lot!

**Comment by cancam** [comment]
Hi again @JappaB,
We have uploaded Python pascal-voc-lrp evaluation kit to the repository.
