### ISSUE TITLE
PASCAL's moLRP divides by _background_ class too

### ISSUE THREAD

**Issue by AlexanderHustinx** [cancam/LRP#4]
Hey there,

First off, interesting work and thanks for the implementation!

Second, I've noticed that in the PASCAL version (did not look at the COCO version as it is not relevant for me) you calculate moLRP by taking the mean over all classes (`self.resultsLRP.olrp.mean()`).
Should you not exclude the `__background__` class, which is always `0` when calculating the mean?
E.g. by `(self.resultsLRP.olrp[1::]).mean()`?

**Comment by cancam** [comment]
Hi @AlexanderHustinx,

Thank you for your interest to our work.
I looked up the issue that you have mentioned and you're right, we are including background classes while calculating  means of oLRP, its component and AP. I've just updated the code, you can check it if you wish: https://github.com/cancam/LRP/blob/77571b175cb394c5739785004fef87e86b789d7b/pascal-voc-lrp/pascal_voc.py#L409.

Baris.
