### ISSUE TITLE
Quick update in COCOevalLRP class to support python3?

### ISSUE THREAD

**Issue by tjiagoM** [cancam/LRP#7]
Hi! I have been using your `cocoevalLRP.py` integrated in my cocoapi python folder (this is the only file I took from your repository)

I had to change this line here:
https://github.com/cancam/LRP/blob/de7bae3887211a605d367c71643a76789384669c/cocoLRPapi-master/PythonAPI/pycocotools/cocoevalLRP.py#L323

to `np.set_printoptions(threshold=sys.maxsize)` because I was constantly getting some errors there. After searching online, it seems that's something that was allowed in numpy on python 2.7, but not anymore.

I'm using python 3, and this was the only change I had to make, so was wondering if you don't want to just change this for a better integration with whoever uses your code. I'm not submitting a PR just because I wouldn't be able to test if this simple change breaks functionality in a python2.7 environment.

Cheers!

**Comment by kemaloksuz** [comment]
Hi!

Thanks for pointing out that. Soon, we will release a new version which does not have this kind of problems. 

Kemal
